name: ElytraNerfPlugin
version: 1.0
main: io.starseed.elytranerfplugin.ElytraNerfPlugin
api-version: 1.13
commands:
  elytranerf:
    description: Set a player's End state
    usage: /elytranerf <player> <true|false>
    permission: elytranerfplugin.admin